### ISSUE TITLE
我是来感谢刘老师的，随便期待下以后的课程

### ISSUE THREAD

**Issue by ofzo** [materliu/gallery-by-react#9]

**Comment by OnStyle** [comment]
我来提交一个问题，不知道问题实在ie还是在代码，我自己写的也是这样，刘老师的也是

环境是ie11，win10版的，edge没问题

图片翻转后，出现了和safari上一样的问题，背面的文字没有显示出来，而是图片和标题反转了

**Comment by OnStyle** [comment]
我的项目也完成了，欢迎刘老师和各位同学提意见，

https://onstyle.github.io/GalleryReactApp
